// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0DghQzBafQQOsC_iFtGgwE6XRs6THctQ',
    appId: '1:1010124734701:web:a7fe21221c1977d590cce4',
    messagingSenderId: '1010124734701',
    projectId: 'flashorder-6640e',
    authDomain: 'flashorder-6640e.firebaseapp.com',
    storageBucket: 'flashorder-6640e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywf9FPz2lMNFFMNRn4OhEvhEYIQBY6NA',
    appId: '1:1010124734701:android:621580224a362ee090cce4',
    messagingSenderId: '1010124734701',
    projectId: 'flashorder-6640e',
    storageBucket: 'flashorder-6640e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6TcFnEtlJeQQnmSgmLE4As6L370xxCs',
    appId: '1:1010124734701:ios:16f2848bf63e2ef890cce4',
    messagingSenderId: '1010124734701',
    projectId: 'flashorder-6640e',
    storageBucket: 'flashorder-6640e.firebasestorage.app',
    iosBundleId: 'com.example.flashOrder',
  );
}
